#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -f 0/alpha.sluge.gz 0/alpha.sluge
rm -rf *Flux

cleanCase
